<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<head>

<meta charset="utf-8" />
<meta name="generator" content="quarto-1.8.25" />

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />


<title>Data Manipulation Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<!-- htmldependencies:E3FAD763 -->
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous" data-relocate-top="true"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Manipulation Challenge</h1>
<p class="subtitle lead">A Mental Model for Method Chaining in Pandas</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="data-manipulation-challenge---a-mental-model-for-method-chaining-in-pandas" class="level1">
<h1>🔗 Data Manipulation Challenge - A Mental Model for Method Chaining in Pandas</h1>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>📊 Challenge Requirements In Section <a href="#student-analysis-section">Student Analysis Section</a>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Complete all discussion questions for the seven mental models (plus some extra requirements for higher grades)</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🎯 Note on Python Usage
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Recommended Workflow: Use Your Existing Virtual Environment</strong> If you completed the Tech Setup Challenge Part 2, you already have a virtual environment set up! Here’s how to use it for this new challenge:</p>
<ol type="1">
<li><strong>Clone this new challenge repository</strong> (see Getting Started section below)</li>
<li><strong>Open the cloned repository in Cursor</strong></li>
<li><strong>Set this project to use your existing Python interpreter:</strong>
<ul>
<li>Press <code>Ctrl+Shift+P</code> → “Python: Select Interpreter”</li>
<li>Navigate to and choose the interpreter from your existing virtual environment (e.g., <code>your-previous-project/venv/Scripts/python.exe</code>)</li>
</ul></li>
<li><strong>Activate the environment in your terminal:</strong>
<ul>
<li>Open terminal in Cursor (`Ctrl + ``)</li>
<li>Navigate to your previous project folder where you have the <code>venv</code> folder</li>
<li><strong>💡 Pro tip:</strong> You can quickly navigate by typing <code>cd</code> followed by dragging the folder from your file explorer into the terminal</li>
<li>Activate using the appropriate command for your system:
<ul>
<li><strong>Windows Command Prompt:</strong> <code>venv\Scripts\activate</code></li>
<li><strong>Windows PowerShell:</strong> <code>.\venv\Scripts\Activate.ps1</code></li>
<li><strong>Mac/Linux:</strong> <code>source venv/bin/activate</code></li>
</ul></li>
<li>You should see <code>(venv)</code> at the beginning of your terminal prompt</li>
</ul></li>
<li><strong>Install additional packages if needed:</strong> <code>pip install pandas numpy matplotlib seaborn</code></li>
</ol>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>⚠️ Cloud Storage Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Avoid using Google Drive, OneDrive, or other cloud storage for Python projects!</strong> These services can cause issues with: - Package installations failing due to file locking - Virtual environment corruption - Slow performance during pip operations</p>
<p><strong>Best practice:</strong> Keep your Python projects in a local folder like <code>C:\Users\YourName\Documents\</code> or <code>~/Documents/</code> instead of cloud-synced folders.</p>
</div>
</div>
<p><strong>Alternative: Create a New Virtual Environment</strong> If you prefer a fresh environment, follow the Quarto documentation: <a href="https://quarto.org/docs/projects/virtual-environments.html">https://quarto.org/docs/projects/virtual-environments.html</a>. Be sure to follow the instructions to activate the environment, set it up as your default Python interpreter for the project, and install the necessary packages (e.g. pandas) for this challenge. For installing the packages, you can use the <code>pip install -r requirements.txt</code> command since you already have the requirements.txt file in your project. Some steps do take a bit of time, so be patient.</p>
<p><strong>Why This Works:</strong> Virtual environments are portable - you can use the same environment across multiple projects, and Cursor automatically activates it when you select the interpreter!</p>
</div>
</div>
<section id="the-problem-mastering-data-manipulation-through-method-chaining" class="level2">
<h2>The Problem: Mastering Data Manipulation Through Method Chaining</h2>
<p><strong>Core Question:</strong> How can we efficiently manipulate datasets using <code>pandas</code> method chaining to answer complex business questions?</p>
<p><strong>The Challenge:</strong> Real-world data analysis requires combining multiple data manipulation techniques in sequence. Rather than creating intermediate variables at each step, method chaining allows us to write clean, readable code that flows logically from one operation to the next.</p>
<p><strong>Our Approach:</strong> We’ll work with ZappTech’s shipment data to answer critical business questions about service levels and cross-category orders, using the seven mental models of data manipulation through pandas method chaining.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>⚠️ AI Partnership Required
</div>
</div>
<div class="callout-body-container callout-body">
<p>This challenge pushes boundaries intentionally. You’ll tackle problems that normally require weeks of study, but with Cursor AI as your partner (and your brain keeping it honest), you can accomplish more than you thought possible.</p>
<p><strong>The new reality:</strong> The four stages of competence are Ignorance → Awareness → Learning → Mastery. AI lets us produce Mastery-level work while operating primarily in the Awareness stage. I focus on awareness training, you leverage AI for execution, and together we create outputs that used to require years of dedicated study.</p>
</div>
</div>
</section>
<section id="the-seven-mental-models-of-data-manipulation" class="level2">
<h2>The Seven Mental Models of Data Manipulation</h2>
<p>The seven most important ways we manipulate datasets are:</p>
<ol type="1">
<li><strong>Assign:</strong> Add new variables with calculations and transformations</li>
<li><strong>Subset:</strong> Filter data based on conditions or select specific columns</li>
<li><strong>Drop:</strong> Remove unwanted variables or observations</li>
<li><strong>Sort:</strong> Arrange data by values or indices</li>
<li><strong>Aggregate:</strong> Summarize data using functions like mean, sum, count</li>
<li><strong>Merge:</strong> Combine information from multiple datasets</li>
<li><strong>Split-Apply-Combine:</strong> Group data and apply functions within groups</li>
</ol>
</section>
<section id="data-and-business-context" class="level2">
<h2>Data and Business Context</h2>
<p>We analyze ZappTech’s shipment data, which contains information about product deliveries across multiple categories. This dataset is ideal for our analysis because:</p>
<ul>
<li><strong>Real Business Questions:</strong> CEO wants to understand service levels and cross-category shopping patterns</li>
<li><strong>Multiple Data Sources:</strong> Requires merging shipment data with product category information</li>
<li><strong>Complex Relationships:</strong> Service levels may vary by product category, and customers may order across categories</li>
<li><strong>Method Chaining Practice:</strong> Perfect for demonstrating all seven mental models in sequence</li>
</ul>
</section>
<section id="data-loading-and-initial-exploration" class="level2">
<h2>Data Loading and Initial Exploration</h2>
<p>Let’s start by loading the ZappTech shipment data and understanding what we’re working with.</p>
<div id="load-data" class="cell" data-message="false" data-execution_count="1">
<div class="sourceCode" id="cb1"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datetime <span class="im">import</span> datetime, timedelta</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the shipment data</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>shipments_df <span class="op">=</span> pd.read_csv(</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;https://raw.githubusercontent.com/flyaflya/persuasive/main/shipments.csv&quot;</span>, </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    parse_dates<span class="op">=</span>[<span class="st">&#39;plannedShipDate&#39;</span>, <span class="st">&#39;actualShipDate&#39;</span>]</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Load product line data</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>product_line_df <span class="op">=</span> pd.read_csv(</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;https://raw.githubusercontent.com/flyaflya/persuasive/main/productLine.csv&quot;</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Reduce dataset size for faster processing (4,000 rows instead of 96,805 rows)</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>shipments_df <span class="op">=</span> shipments_df.head(<span class="dv">4000</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Shipments data shape:&quot;</span>, shipments_df.shape)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Shipments data columns:&quot;</span>, shipments_df.columns.tolist())</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">First few rows of shipments data:&quot;</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shipments_df.head(<span class="dv">10</span>))</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span> <span class="op">+</span> <span class="st">&quot;=&quot;</span><span class="op">*</span><span class="dv">50</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Product line data shape:&quot;</span>, product_line_df.shape)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Product line data columns:&quot;</span>, product_line_df.columns.tolist())</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">First few rows of product line data:&quot;</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(product_line_df.head(<span class="dv">10</span>))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Shipments data shape: (4000, 5)

Shipments data columns: [&#39;shipID&#39;, &#39;plannedShipDate&#39;, &#39;actualShipDate&#39;, &#39;partID&#39;, &#39;quantity&#39;]

First few rows of shipments data:
   shipID plannedShipDate actualShipDate       partID  quantity
0   10001      2013-11-06     2013-10-04  part92b16c5         6
1   10002      2013-10-15     2013-10-04   part66983b         2
2   10003      2013-10-25     2013-10-07  part8e36f25         1
3   10004      2013-10-14     2013-10-08  part30f5de0         1
4   10005      2013-10-14     2013-10-08  part9d64d35         6
5   10006      2013-10-14     2013-10-08  part6cd6167        15
6   10007      2013-10-14     2013-10-08  parta4d5fd1         2
7   10008      2013-10-14     2013-10-08  part08cadf5         1
8   10009      2013-10-14     2013-10-08  part5cc4989        10
9   10010      2013-10-14     2013-10-08  part912ae4c         1

==================================================
Product line data shape: (11997, 3)

Product line data columns: [&#39;partID&#39;, &#39;productLine&#39;, &#39;prodCategory&#39;]

First few rows of product line data:
        partID productLine prodCategory
0  part00005ba      line4c      Liquids
1  part000b57d      line61     Machines
2  part00123bf      linec1  Marketables
3  part0021fc9      line61     Machines
4  part0027e86      line2f     Machines
5  part002ed95      line4c      Liquids
6  part0030856      lineb8     Machines
7  part0033dfd      line49      Liquids
8  part0037a2a      linea3  Marketables
9  part003caee      linea3  Marketables</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>💡 Understanding the Data
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Shipments Data:</strong> Contains individual line items for each shipment, including: - <code>shipID</code>: Unique identifier for each shipment - <code>partID</code>: Product identifier - <code>plannedShipDate</code>: When the shipment was supposed to go out - <code>actualShipDate</code>: When it actually shipped - <code>quantity</code>: How many units were shipped</p>
<p><strong>Product Category and Line Data:</strong> Contains product category information: - <code>partID</code>: Links to shipments data - <code>productLine</code>: The category each product belongs to - <code>prodCategory</code>: The category each product belongs to</p>
<p><strong>Business Questions We’ll Answer:</strong> 1. Does service level (on-time shipments) vary across product categories? 2. How often do orders include products from more than one category?</p>
</div>
</div>
</section>
<section id="the-seven-mental-models-a-progressive-learning-journey" class="level2">
<h2>The Seven Mental Models: A Progressive Learning Journey</h2>
<p>Now we’ll work through each of the seven mental models using method chaining, starting simple and building complexity.</p>
<section id="assign-adding-new-variables" class="level3">
<h3>1. Assign: Adding New Variables</h3>
<p><strong>Mental Model:</strong> Create new columns with calculations and transformations.</p>
<p>Let’s start by calculating whether each shipment was late:</p>
<div id="mental-model-1-assign" class="cell" data-execution_count="2">
<div class="sourceCode" id="cb3"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple assignment - calculate if shipment was late</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>shipments_with_lateness <span class="op">=</span> (</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    shipments_df</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    .assign(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>        is_late<span class="op">=</span><span class="kw">lambda</span> df: df[<span class="st">&#39;actualShipDate&#39;</span>] <span class="op">&gt;</span> df[<span class="st">&#39;plannedShipDate&#39;</span>],</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        days_late<span class="op">=</span><span class="kw">lambda</span> df: (df[<span class="st">&#39;actualShipDate&#39;</span>] <span class="op">-</span> df[<span class="st">&#39;plannedShipDate&#39;</span>]).dt.days</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Added lateness calculations:&quot;</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shipments_with_lateness[[<span class="st">&#39;shipID&#39;</span>, <span class="st">&#39;plannedShipDate&#39;</span>, <span class="st">&#39;actualShipDate&#39;</span>, <span class="st">&#39;is_late&#39;</span>, <span class="st">&#39;days_late&#39;</span>]].head())</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Added lateness calculations:
   shipID plannedShipDate actualShipDate  is_late  days_late
0   10001      2013-11-06     2013-10-04    False        -33
1   10002      2013-10-15     2013-10-04    False        -11
2   10003      2013-10-25     2013-10-07    False        -18
3   10004      2013-10-14     2013-10-08    False         -6
4   10005      2013-10-14     2013-10-08    False         -6</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>💡 Method Chaining Tip for New Python Users
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Why use <code>lambda df:</code>?</strong> When chaining methods, we need to reference the current state of the dataframe. The <code>lambda df:</code> tells pandas “use the current dataframe in this calculation.” Without it, pandas would look for a variable called <code>df</code> that doesn’t exist.</p>
<p><strong>Alternative approach:</strong> You could also write this as separate steps, but method chaining keeps related operations together and makes the code more readable.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🤔 Discussion Questions: Assign Mental Model
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Question 1: Data Types and Date Handling</strong> - What is the <code>dtype</code> of the <code>actualShipDate</code> series? How can you find out using code? - Why is it important that both <code>actualShipDate</code> and <code>plannedShipDate</code> have the same data type for comparison?</p>
<p><strong>Question 2: String vs Date Comparison</strong> - Can you give an example where comparing two dates as strings would yield unintuitive results, e.g. what happens if you try to compare “04-11-2025” and “05-20-2024” as strings vs as dates?</p>
<p><strong>Question 3: Debug This Code</strong></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This code has an error - can you spot it?</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>shipments_with_lateness <span class="op">=</span> (</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    shipments_df</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    .assign(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        is_late<span class="op">=</span><span class="kw">lambda</span> df: df[<span class="st">&#39;actualShipDate&#39;</span>] <span class="op">&gt;</span> df[<span class="st">&#39;plannedShipDate&#39;</span>],</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        days_late<span class="op">=</span><span class="kw">lambda</span> df: (df[<span class="st">&#39;actualShipDate&#39;</span>] <span class="op">-</span> df[<span class="st">&#39;plannedShipDate&#39;</span>]).dt.days,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        lateStatement<span class="op">=</span><span class="kw">lambda</span> df: df[<span class="st">&#39;is_late&#39;</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="st">&quot;Darn Shipment is Late&quot;</span> <span class="cf">if</span> x <span class="cf">else</span> <span class="st">&quot;Shipment is on Time&quot;</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>What’s wrong with the <code>lateStatement</code> assignment and how would you fix it?</p>
</div>
</div>
<section id="briefly-give-answers-to-the-discussion-questions-in-this-section" class="level4">
<h4>Briefly Give Answers to the Discussion Questions In This Section</h4>
<blockquote>
<p>Replace this with your answers to the discussion questions</p>
</blockquote>
<div id="543bacd5" class="cell" data-execution_count="3">
<div class="sourceCode" id="cb6"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple assignment - calculate if shipment was late</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shipments_df[<span class="st">&#39;actualShipDate&#39;</span>].dtype)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>datetime64[ns]</code></pre>
</div>
</div>
<p>1.The dtype of actualShipDate is datetime64[ns] because when we loaded the data, we used parse_dates=[‘plannedShipDate’, ‘actualShipDate’] which converted these columns from strings to datetime objects. 2.It is important that both actualShipDate and plannedShipDate have the same data type for comparison because if they are not the same data type, pandas will not be able to compare them. .String vs Date Comparison Problem</p>
<p>When comparing dates as strings, the computer evaluates them alphabetically character-by-character rather than chronologically. This leads to incorrect results because string comparison doesn’t understand calendar logic.</p>
<p>The Problem:</p>
<p>String comparison: “04-11-2025” vs “05-20-2024” → False (wrong)</p>
<p>Date comparison: April 11, 2025 vs May 20, 2024 → True (correct)</p>
<p>3.Debug This Code Answer: The error occurs because shipments_df[‘is_late’] doesn’t exist in the original dataframe - it’s being created in the same assign() call. The fix is to use the lambda approach:</p>
<div id="860f82f1" class="cell" data-execution_count="4">
<div class="sourceCode" id="cb8"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>shipments_with_lateness <span class="op">=</span> (</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    shipments_df</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    .assign(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>        is_late<span class="op">=</span><span class="kw">lambda</span> df: df[<span class="st">&#39;actualShipDate&#39;</span>] <span class="op">&gt;</span> df[<span class="st">&#39;plannedShipDate&#39;</span>],</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>        days_late<span class="op">=</span><span class="kw">lambda</span> df: (df[<span class="st">&#39;actualShipDate&#39;</span>] <span class="op">-</span> df[<span class="st">&#39;plannedShipDate&#39;</span>]).dt.days,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>        lateStatement<span class="op">=</span><span class="kw">lambda</span> df: df[<span class="st">&#39;is_late&#39;</span>].<span class="bu">apply</span>(</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>            <span class="kw">lambda</span> x: <span class="st">&quot;Darn Shipment is Late&quot;</span> <span class="cf">if</span> x <span class="cf">else</span> <span class="st">&quot;Shipment is on Time&quot;</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
</div>
</section>
</section>
<section id="subset-querying-rows-and-filtering-columns" class="level3">
<h3>2. Subset: Querying Rows and Filtering Columns</h3>
<p><strong>Mental Model:</strong> Query rows based on conditions and filter to keep specific columns.</p>
<p>Let’s query for only late shipments and filter to keep the columns we need:</p>
<div id="mental-model-2-subset" class="cell" data-execution_count="5">
<div class="sourceCode" id="cb9"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Query rows for late shipments and filter to keep specific columns</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>late_shipments <span class="op">=</span> (</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    shipments_with_lateness</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    .query(<span class="st">&#39;is_late == True&#39;</span>)  <span class="co"># Query rows where is_late is True</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>([<span class="st">&#39;shipID&#39;</span>, <span class="st">&#39;partID&#39;</span>, <span class="st">&#39;plannedShipDate&#39;</span>, <span class="st">&#39;actualShipDate&#39;</span>, <span class="st">&#39;days_late&#39;</span>])  <span class="co"># Filter to keep specific columns</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Found </span><span class="sc">{</span><span class="bu">len</span>(late_shipments)<span class="sc">}</span><span class="ss"> late shipments out of </span><span class="sc">{</span><span class="bu">len</span>(shipments_with_lateness)<span class="sc">}</span><span class="ss"> total&quot;</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Late shipments sample:&quot;</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(late_shipments.head())</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Found 456 late shipments out of 4000 total

Late shipments sample:
     shipID       partID plannedShipDate actualShipDate  days_late
776   10192  part0164a70      2013-10-09     2013-10-14          5
777   10192  part9259836      2013-10-09     2013-10-14          5
778   10192  part4526c73      2013-10-09     2013-10-14          5
779   10192  partbb47e81      2013-10-09     2013-10-14          5
780   10192  part008482f      2013-10-09     2013-10-14          5</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>🔍 Understanding the Methods
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong><code>.query()</code></strong>: Query rows based on conditions (like SQL WHERE clause)</li>
<li><strong><code>.filter()</code></strong>: Filter to keep specific columns by name</li>
<li><strong>Alternative</strong>: You could use <code>.loc[]</code> for more complex row querying, but <code>.query()</code> is often more readable</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🤔 Discussion Questions: Subset Mental Model
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Question 1: Query vs Boolean Indexing</strong> - What’s the difference between using <code>.query('is_late == True')</code> and <code>[df['is_late'] == True]</code>? - Which approach is more readable and why?</p>
<p><strong>Question 2: Additional Row Querying</strong> - Can you show an example of using a variable like <code>late_threshold</code> to query rows for shipments that are at least <code>late_threshold</code> days late, e.g. what if you wanted to query rows for shipments that are at least 5 days late?</p>
</div>
</div>
<section id="briefly-give-answers-to-the-discussion-questions-in-this-section-1" class="level4">
<h4>Briefly Give Answers to the Discussion Questions In This Section</h4>
<p>1 .query() - More readable, SQL-like syntax:</p>
<p>Boolean indexing - More verbose: Performance &amp; Memory .query() - Often faster for large datasets because it uses pandas’ optimized query engine</p>
<p>Boolean indexing - Creates an intermediate boolean series, which uses more memory</p>
<p>Flexibility .query() - Can use variables with @ symbol:</p>
<p>Boolean indexing - Variables work directly: Bottom line: .query() is generally more readable, especially in method chains, while boolean indexing gives you more explicit control.</p>
<p>2..query() is more readable, especially in method chains.</p>
<div id="cell-mental-model-2-subset-examples" class="cell" data-execution_count="6">
<div class="sourceCode" id="cb11"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># .query() - reads like natural language</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>(shipments_with_lateness</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    .query(<span class="st">&#39;is_late == True&#39;</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>([<span class="st">&#39;shipID&#39;</span>, <span class="st">&#39;partID&#39;</span>, <span class="st">&#39;days_late&#39;</span>])</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<div id="mental-model-2-subset-examples" class="cell-output cell-output-display" data-execution_count="6">
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">shipID</th>
<th data-quarto-table-cell-role="th">partID</th>
<th data-quarto-table-cell-role="th">days_late</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">776</td>
<td>10192</td>
<td>part0164a70</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">777</td>
<td>10192</td>
<td>part9259836</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">778</td>
<td>10192</td>
<td>part4526c73</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">779</td>
<td>10192</td>
<td>partbb47e81</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">780</td>
<td>10192</td>
<td>part008482f</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3896</td>
<td>10956</td>
<td>part98c1c48</td>
<td>21</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3897</td>
<td>10956</td>
<td>part82e69e9</td>
<td>21</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3898</td>
<td>10956</td>
<td>partf23fd1e</td>
<td>21</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3899</td>
<td>10956</td>
<td>part825873c</td>
<td>21</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3997</td>
<td>11001</td>
<td>partd4952a8</td>
<td>11</td>
</tr>
</tbody>
</table>

<p>456 rows × 3 columns</p>
</div>
</div>
</div>
<p>Boolean indexing breaks the flow:</p>
<div id="e1a84a6e" class="cell" data-execution_count="7">
<div class="sourceCode" id="cb12"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boolean indexing - more cluttered</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>(shipments_with_lateness[shipments_with_lateness[<span class="st">&#39;is_late&#39;</span>] <span class="op">==</span> <span class="va">True</span>]</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>([<span class="st">&#39;shipID&#39;</span>, <span class="st">&#39;partID&#39;</span>, <span class="st">&#39;days_late&#39;</span>])</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">shipID</th>
<th data-quarto-table-cell-role="th">partID</th>
<th data-quarto-table-cell-role="th">days_late</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">776</td>
<td>10192</td>
<td>part0164a70</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">777</td>
<td>10192</td>
<td>part9259836</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">778</td>
<td>10192</td>
<td>part4526c73</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">779</td>
<td>10192</td>
<td>partbb47e81</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">780</td>
<td>10192</td>
<td>part008482f</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3896</td>
<td>10956</td>
<td>part98c1c48</td>
<td>21</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3897</td>
<td>10956</td>
<td>part82e69e9</td>
<td>21</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3898</td>
<td>10956</td>
<td>partf23fd1e</td>
<td>21</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3899</td>
<td>10956</td>
<td>part825873c</td>
<td>21</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3997</td>
<td>11001</td>
<td>partd4952a8</td>
<td>11</td>
</tr>
</tbody>
</table>

<p>456 rows × 3 columns</p>
</div>
</div>
</div>
<ol start="3" type="1">
<li>Using .query() with variables: 5 days late:</li>
</ol>
<div id="7bece8cd" class="cell" data-execution_count="8">
<div class="sourceCode" id="cb13"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define threshold</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>late_threshold <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Query using @ symbol for variables</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>very_late_shipments <span class="op">=</span> (</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    shipments_with_lateness</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    .query(<span class="st">&#39;days_late &gt;= @late_threshold&#39;</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>([<span class="st">&#39;shipID&#39;</span>, <span class="st">&#39;partID&#39;</span>, <span class="st">&#39;days_late&#39;</span>, <span class="st">&#39;is_late&#39;</span>])</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Found </span><span class="sc">{</span><span class="bu">len</span>(very_late_shipments)<span class="sc">}</span><span class="ss"> shipments at least </span><span class="sc">{</span>late_threshold<span class="sc">}</span><span class="ss"> days late&quot;</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(very_late_shipments.head())</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Found 186 shipments at least 5 days late
     shipID       partID  days_late  is_late
776   10192  part0164a70          5     True
777   10192  part9259836          5     True
778   10192  part4526c73          5     True
779   10192  partbb47e81          5     True
780   10192  part008482f          5     True</code></pre>
</div>
</div>
<p>Using boolean indexing with variables:</p>
<div id="ae73e642" class="cell" data-execution_count="9">
<div class="sourceCode" id="cb15"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define threshold</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>late_threshold <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Boolean indexing with variables</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>very_late_shipments <span class="op">=</span> (</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    shipments_with_lateness[</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>        shipments_with_lateness[<span class="st">&#39;days_late&#39;</span>] <span class="op">&gt;=</span> late_threshold</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>([<span class="st">&#39;shipID&#39;</span>, <span class="st">&#39;partID&#39;</span>, <span class="st">&#39;days_late&#39;</span>, <span class="st">&#39;is_late&#39;</span>])</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Found </span><span class="sc">{</span><span class="bu">len</span>(very_late_shipments)<span class="sc">}</span><span class="ss"> shipments at least </span><span class="sc">{</span>late_threshold<span class="sc">}</span><span class="ss"> days late&quot;</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(very_late_shipments.head())</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Found 186 shipments at least 5 days late
     shipID       partID  days_late  is_late
776   10192  part0164a70          5     True
777   10192  part9259836          5     True
778   10192  part4526c73          5     True
779   10192  partbb47e81          5     True
780   10192  part008482f          5     True</code></pre>
</div>
</div>
<p>Multiple thresholds example:</p>
<div id="0aaefd68" class="cell" data-execution_count="10">
<div class="sourceCode" id="cb17"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiple threshold variables</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>min_days_late <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>max_days_late <span class="op">=</span> <span class="dv">15</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Using .query() with multiple variables</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>moderately_late <span class="op">=</span> (</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    shipments_with_lateness</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    .query(<span class="st">&#39;days_late &gt;= @min_days_late and days_late &lt;= @max_days_late&#39;</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    .sort_values(<span class="st">&#39;days_late&#39;</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Shipments </span><span class="sc">{</span>min_days_late<span class="sc">}</span><span class="ss">-</span><span class="sc">{</span>max_days_late<span class="sc">}</span><span class="ss"> days late: </span><span class="sc">{</span><span class="bu">len</span>(moderately_late)<span class="sc">}</span><span class="ss">&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Shipments 5-15 days late: 128</code></pre>
</div>
</div>
<p>Key difference in variable usage: .query(): Use <span class="citation" data-cites="variable_name">@variable_name</span> syntax</p>
<p>Boolean indexing: Use variables directly This approach makes code more flexible and reusable - you can easily change the threshold without modifying the query logic.</p>
</section>
</section>
<section id="drop-removing-unwanted-data" class="level3">
<h3>3. Drop: Removing Unwanted Data</h3>
<p><strong>Mental Model:</strong> Remove columns or rows you don’t need.</p>
<p>Let’s clean up our data by removing unnecessary columns:</p>
<div id="mental-model-3-drop" class="cell" data-execution_count="11">
<div class="sourceCode" id="cb19"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a cleaner dataset by dropping unnecessary columns</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>clean_shipments <span class="op">=</span> (</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    shipments_with_lateness</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    .drop(columns<span class="op">=</span>[<span class="st">&#39;quantity&#39;</span>])  <span class="co"># Drop quantity column (not needed for our analysis)</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    .dropna(subset<span class="op">=</span>[<span class="st">&#39;plannedShipDate&#39;</span>, <span class="st">&#39;actualShipDate&#39;</span>])  <span class="co"># Remove rows with missing dates</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Cleaned dataset: </span><span class="sc">{</span><span class="bu">len</span>(clean_shipments)<span class="sc">}</span><span class="ss"> rows, </span><span class="sc">{</span><span class="bu">len</span>(clean_shipments.columns)<span class="sc">}</span><span class="ss"> columns&quot;</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Remaining columns:&quot;</span>, clean_shipments.columns.tolist())</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cleaned dataset: 4000 rows, 7 columns
Remaining columns: [&#39;shipID&#39;, &#39;plannedShipDate&#39;, &#39;actualShipDate&#39;, &#39;partID&#39;, &#39;is_late&#39;, &#39;days_late&#39;, &#39;lateStatement&#39;]</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🤔 Discussion Questions: Drop Mental Model
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Question 1: Drop vs Filter Strategies</strong> - What’s the difference between <code>.drop(columns=['quantity'])</code> and <code>.filter()</code> with a list of columns you want to keep? - When would you choose to drop columns vs filter to keep specific columns?</p>
<p><strong>Question 2: Handling Missing Data</strong> - What happens if you use <code>.dropna()</code> without specifying <code>subset</code>? How is this different from <code>.dropna(subset=['plannedShipDate', 'actualShipDate'])</code>? - Why might you want to be selective about which columns to check for missing values?</p>
</div>
</div>
<section id="briefly-give-answers-to-the-discussion-questions-in-this-section-2" class="level4">
<h4>Briefly Give Answers to the Discussion Questions In This Section</h4>
<ol type="1">
<li></li>
</ol>
<p>Question 1: Drop vs Filter Strategies</p>
<p>.drop(columns=[‘quantity’]) Removes only the specified columns Keeps all other columns Use when you want to remove a few specific columns from many .filter([‘col1’, ‘col2’]) Keeps only the columns you list Removes all other columns Use when you want to keep only a specific subset of columns</p>
<div id="6e6eb8af" class="cell" data-execution_count="12">
<div class="sourceCode" id="cb21"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># These are equivalent for column selection:</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>method1 <span class="op">=</span> shipments_df.drop(columns<span class="op">=</span>[<span class="st">&#39;quantity&#39;</span>])  <span class="co"># Explicit removal</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>method2 <span class="op">=</span> shipments_df.<span class="bu">filter</span>([<span class="st">&#39;shipID&#39;</span>, <span class="st">&#39;plannedShipDate&#39;</span>, <span class="st">&#39;actualShipDate&#39;</span>, <span class="st">&#39;partID&#39;</span>])  <span class="co"># Explicit inclusion</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Same columns:&quot;</span>, <span class="bu">set</span>(method1.columns) <span class="op">==</span> <span class="bu">set</span>(method2.columns))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Same columns: True</code></pre>
</div>
</div>
<p>Answer: Use .drop() when you know exactly which few columns to remove. Use .filter() when you want to keep a specific subset of columns, especially when you have many columns and only need a few.</p>
<p>2.To avoid losing good data unnecessarily</p>
<p>Example: A row has:</p>
<p>plannedShipDate: 2023-10-15 ✅</p>
<p>actualShipDate: 2023-10-14 ✅</p>
<p>customerNotes: NaN (missing)</p>
<p>.dropna() without subset: ❌ Removes the entire row because customerNotes is missing</p>
<p>.dropna(subset=[‘plannedShipDate’]): ✅ Keeps the row because the important date columns have data</p>
<p>Why be selective:</p>
<p>Keep rows where critical columns have data</p>
<p>Don’t care if optional columns are missing</p>
<p>Preserve more data for analysis</p>
<p>Avoid deleting useful information</p>
<div id="6a389bf5" class="cell" data-execution_count="13">
<div class="sourceCode" id="cb23"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Without subset - drops rows with ANY missing values</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>dropped_any_na <span class="op">=</span> shipments_df.dropna()</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Rows after dropping any NA: </span><span class="sc">{</span><span class="bu">len</span>(dropped_any_na)<span class="sc">}</span><span class="ss">&quot;</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># With subset - only checks specific columns</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>dropped_selected_na <span class="op">=</span> shipments_df.dropna(subset<span class="op">=</span>[<span class="st">&#39;plannedShipDate&#39;</span>, <span class="st">&#39;actualShipDate&#39;</span>])</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Rows after dropping date NAs: </span><span class="sc">{</span><span class="bu">len</span>(dropped_selected_na)<span class="sc">}</span><span class="ss">&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows after dropping any NA: 4000
Rows after dropping date NAs: 4000</code></pre>
</div>
</div>
<p>Using .dropna() without subset can remove valuable data unnecessarily. Being selective with subset ensures we only remove rows where critical fields are missing, preserving other useful data.</p>
</section>
</section>
<section id="sort-arranging-data" class="level3">
<h3>4. Sort: Arranging Data</h3>
<p><strong>Mental Model:</strong> Order data by values or indices.</p>
<p>Let’s sort by lateness to see the worst offenders:</p>
<div id="mental-model-4-sort" class="cell" data-execution_count="14">
<div class="sourceCode" id="cb25"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort by days late (worst first)</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>sorted_by_lateness <span class="op">=</span> (</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    clean_shipments</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    .sort_values(<span class="st">&#39;days_late&#39;</span>, ascending<span class="op">=</span><span class="va">False</span>)  <span class="co"># Sort by days_late, highest first</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    .reset_index(drop<span class="op">=</span><span class="va">True</span>)  <span class="co"># Reset index to be sequential</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Shipments sorted by lateness (worst first):&quot;</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sorted_by_lateness[[<span class="st">&#39;shipID&#39;</span>, <span class="st">&#39;partID&#39;</span>, <span class="st">&#39;days_late&#39;</span>, <span class="st">&#39;is_late&#39;</span>]].head(<span class="dv">10</span>))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Shipments sorted by lateness (worst first):
   shipID       partID  days_late  is_late
0   10956  partb6208b5         21     True
1   10956  part04ef2f7         21     True
2   10956  part4875f85         21     True
3   10956  partb722d53         21     True
4   10956  partc979912         21     True
5   10956  parta27d449         21     True
6   10956  partc653823         21     True
7   10956  part82e69e9         21     True
8   10956  partf23fd1e         21     True
9   10956  part825873c         21     True</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🤔 Discussion Questions: Sort Mental Model
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Question 1: Sorting Strategies</strong> - What’s the difference between <code>ascending=False</code> and <code>ascending=True</code> in sorting? - How would you sort by multiple columns (e.g., first by <code>is_late</code>, then by <code>days_late</code>)?</p>
<p><strong>Question 2: Index Management</strong> - Why do we use <code>.reset_index(drop=True)</code> after sorting? - What happens to the original index when you sort? Why might this be problematic?</p>
</div>
</div>
<section id="briefly-give-answers-to-the-discussion-questions-in-this-section-3" class="level4">
<h4>Briefly Give Answers to the Discussion Questions In This Section</h4>
<ol type="1">
<li>ascending=True (default):</li>
</ol>
<p>Sorts from lowest to highest</p>
<p>A-Z, 0-9, earliest to latest dates</p>
<p>Example: [1, 3, 5, 7]</p>
<p>ascending=False:</p>
<p>Sorts from highest to lowest</p>
<p>Z-A, 9-0, latest to earliest dates</p>
<p>Example: [7, 5, 3, 1]</p>
<div id="5403c63b" class="cell" data-execution_count="15">
<div class="sourceCode" id="cb27"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Worst lateness first (highest days_late at top)</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>shipments_with_lateness.sort_values(<span class="st">&#39;days_late&#39;</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Best lateness first (lowest days_late at top)  </span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>shipments_with_lateness.sort_values(<span class="st">&#39;days_late&#39;</span>, ascending<span class="op">=</span><span class="va">True</span>)</span></code></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">shipID</th>
<th data-quarto-table-cell-role="th">plannedShipDate</th>
<th data-quarto-table-cell-role="th">actualShipDate</th>
<th data-quarto-table-cell-role="th">partID</th>
<th data-quarto-table-cell-role="th">quantity</th>
<th data-quarto-table-cell-role="th">is_late</th>
<th data-quarto-table-cell-role="th">days_late</th>
<th data-quarto-table-cell-role="th">lateStatement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>10001</td>
<td>2013-11-06</td>
<td>2013-10-04</td>
<td>part92b16c5</td>
<td>6</td>
<td>False</td>
<td>-33</td>
<td>Shipment is on Time</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">289</td>
<td>10059</td>
<td>2013-11-05</td>
<td>2013-10-11</td>
<td>part6667ad</td>
<td>4</td>
<td>False</td>
<td>-25</td>
<td>Shipment is on Time</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">295</td>
<td>10059</td>
<td>2013-11-05</td>
<td>2013-10-11</td>
<td>part0987f63</td>
<td>2</td>
<td>False</td>
<td>-25</td>
<td>Shipment is on Time</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">296</td>
<td>10059</td>
<td>2013-11-05</td>
<td>2013-10-11</td>
<td>partf194391</td>
<td>3</td>
<td>False</td>
<td>-25</td>
<td>Shipment is on Time</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">293</td>
<td>10059</td>
<td>2013-11-05</td>
<td>2013-10-11</td>
<td>partda5110b</td>
<td>1</td>
<td>False</td>
<td>-25</td>
<td>Shipment is on Time</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3881</td>
<td>10956</td>
<td>2013-09-24</td>
<td>2013-10-15</td>
<td>parta27d449</td>
<td>1</td>
<td>True</td>
<td>21</td>
<td>Darn Shipment is Late</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3882</td>
<td>10956</td>
<td>2013-09-24</td>
<td>2013-10-15</td>
<td>partc63f9bc</td>
<td>1</td>
<td>True</td>
<td>21</td>
<td>Darn Shipment is Late</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3883</td>
<td>10956</td>
<td>2013-09-24</td>
<td>2013-10-15</td>
<td>part04ef2f7</td>
<td>1</td>
<td>True</td>
<td>21</td>
<td>Darn Shipment is Late</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3884</td>
<td>10956</td>
<td>2013-09-24</td>
<td>2013-10-15</td>
<td>part4875f85</td>
<td>1</td>
<td>True</td>
<td>21</td>
<td>Darn Shipment is Late</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3894</td>
<td>10956</td>
<td>2013-09-24</td>
<td>2013-10-15</td>
<td>part795d1a4</td>
<td>3</td>
<td>True</td>
<td>21</td>
<td>Darn Shipment is Late</td>
</tr>
</tbody>
</table>

<p>4000 rows × 8 columns</p>
</div>
</div>
</div>
<p>1 b.</p>
<div id="b8010706" class="cell" data-execution_count="16">
<div class="sourceCode" id="cb28"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort by multiple columns</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>sorted_df <span class="op">=</span> shipments_with_lateness.sort_values(</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    [<span class="st">&#39;is_late&#39;</span>, <span class="st">&#39;days_late&#39;</span>], </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    ascending<span class="op">=</span>[<span class="va">False</span>, <span class="va">False</span>]  <span class="co"># is_late: False, days_late: False</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sorted_df[[<span class="st">&#39;shipID&#39;</span>, <span class="st">&#39;is_late&#39;</span>, <span class="st">&#39;days_late&#39;</span>]].head(<span class="dv">10</span>))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      shipID  is_late  days_late
1144   10217     True         21
3879   10956     True         21
3880   10956     True         21
3881   10956     True         21
3882   10956     True         21
3883   10956     True         21
3884   10956     True         21
3885   10956     True         21
3886   10956     True         21
3887   10956     True         21</code></pre>
</div>
</div>
<p>What this does:</p>
<p>First sorts by is_late (False → True, so True appears first)</p>
<p>Then sorts by days_late within each is_late group (highest days_late first)</p>
<p>Result order:</p>
<p>Late shipments (is_late=True) appear first</p>
<p>Within late shipments, most days late appear first</p>
<p>Then on-time shipments (is_late=False)</p>
<p>Within on-time shipments, most days late appear first</p>
<p>2 a.</p>
<p>.reset_index(drop=True) after sorting:</p>
<p>What it does:</p>
<p>Resets the row index to be sequential (0, 1, 2, 3…)</p>
<p>drop=True removes the old index (doesn’t keep it as a column)</p>
<p>Why we need it: After sorting, the original index gets messed up:</p>
<p>Index might be: [45, 12, 8, 33, 1…] (random order)</p>
<p>After reset: [0, 1, 2, 3, 4…] (clean order)</p>
<div id="f09b0fee" class="cell" data-execution_count="17">
<div class="sourceCode" id="cb30"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Without reset_index - messy index</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>sorted_messy <span class="op">=</span> shipments_with_lateness.sort_values(<span class="st">&#39;days_late&#39;</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sorted_messy.index)  <span class="co"># [776, 777, 778, 779, 780...]</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co"># With reset_index - clean index  </span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>sorted_clean <span class="op">=</span> shipments_with_lateness.sort_values(<span class="st">&#39;days_late&#39;</span>, ascending<span class="op">=</span><span class="va">False</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sorted_clean.index)  <span class="co"># [0, 1, 2, 3, 4...]</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Index([3888, 3883, 3884, 3885, 3886, 3881, 3887, 3897, 3898, 3899,
       ...
        299,  298,  293,  304,  324,  323,  320,  321,  322,    0],
      dtype=&#39;int64&#39;, length=4000)
RangeIndex(start=0, stop=4000, step=1)</code></pre>
</div>
</div>
<p>Why this matters:</p>
<p>Clean indexes are easier to work with</p>
<p>Prevents confusion when referencing rows</p>
<p>Some operations expect sequential indexes</p>
<p>2b.</p>
<p>What happens to original index when sorting:</p>
<p>The index stays with the same rows but gets shuffled</p>
<p>Example: Row that was at index 5 might move to index 150 after sorting</p>
<p>Why this is problematic:</p>
<p>Confusing row references:</p>
<p>::: {#92c0adbf .cell execution_count=18} <code>{.python .cell-code}  # After sorting, index 0 might not be the first original row  sorted_df.iloc[0] # This might have been row 45 in original data</code></p>
<p>::: {.cell-output .cell-output-display execution_count=18} <code>shipID                             10217  plannedShipDate      2013-09-23 00:00:00  actualShipDate       2013-10-14 00:00:00  partID                       part2081be9  quantity                               5  is_late                             True  days_late                             21  lateStatement      Darn Shipment is Late  Name: 1144, dtype: object</code> ::: :::</p>
<p>Broken relationships:</p>
<p>If you had external references to row indexes, they’re now wrong</p>
<p>Messy display:</p>
<p>Index shows random numbers: [45, 12, 8, 33, 1…]</p>
<p>Hard to see the actual sorted order</p>
<p>Some functions expect sequential indexes:</p>
<p>Plotting, some pandas operations work better with clean 0,1,2,3… indexes</p>
</section>
</section>
<section id="aggregate-summarizing-data" class="level3">
<h3>5. Aggregate: Summarizing Data</h3>
<p><strong>Mental Model:</strong> Calculate summary statistics across groups or the entire dataset.</p>
<p>Let’s calculate overall service level metrics:</p>
<div id="mental-model-5-aggregate" class="cell" data-execution_count="19">
<div class="sourceCode" id="cb32"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate overall service level metrics</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>service_metrics <span class="op">=</span> (</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    clean_shipments</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    .agg({</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">&#39;is_late&#39;</span>: [<span class="st">&#39;count&#39;</span>, <span class="st">&#39;sum&#39;</span>, <span class="st">&#39;mean&#39;</span>],  <span class="co"># Count total, count late, calculate percentage</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">&#39;days_late&#39;</span>: [<span class="st">&#39;mean&#39;</span>, <span class="st">&#39;max&#39;</span>]  <span class="co"># Average and maximum days late</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Overall Service Level Metrics:&quot;</span>)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(service_metrics)</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage on-time directly from the data</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>on_time_rate <span class="op">=</span> (<span class="dv">1</span> <span class="op">-</span> clean_shipments[<span class="st">&#39;is_late&#39;</span>].mean()) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;</span><span class="ch">\n</span><span class="ss">On-time delivery rate: </span><span class="sc">{</span>on_time_rate<span class="sc">:.1f}</span><span class="ss">%&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Service Level Metrics:
        is_late  days_late
count  4000.000        NaN
sum     456.000        NaN
mean      0.114     -0.974
max         NaN     21.000

On-time delivery rate: 88.6%</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🤔 Discussion Questions: Aggregate Mental Model
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Question 1: Boolean Aggregation</strong> - Why does <code>sum()</code> work on boolean values? What does it count?</p>
</div>
</div>
<section id="briefly-give-answers-to-the-discussion-questions-in-this-section-4" class="level4">
<h4>Briefly Give Answers to the Discussion Questions In This Section</h4>
<p>Why sum() works on boolean values:</p>
<p>In Python/pandas, True = 1 and False = 0</p>
<p>What sum() counts:</p>
<p>It counts how many True values (1’s) are in the boolean series</p>
<p>Each True = 1, each False = 0</p>
<div id="e77425b0" class="cell" data-execution_count="20">
<div class="sourceCode" id="cb34"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First create clean_shipments (from earlier cells)</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>clean_shipments <span class="op">=</span> (</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    shipments_with_lateness</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    .drop(columns<span class="op">=</span>[<span class="st">&#39;quantity&#39;</span>])  <span class="co"># Drop quantity column</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    .dropna(subset<span class="op">=</span>[<span class="st">&#39;plannedShipDate&#39;</span>, <span class="st">&#39;actualShipDate&#39;</span>])  <span class="co"># Remove rows with missing dates</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Then calculate service metrics</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>service_metrics <span class="op">=</span> (</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    clean_shipments</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    .agg({</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">&#39;is_late&#39;</span>: [<span class="st">&#39;count&#39;</span>, <span class="st">&#39;sum&#39;</span>, <span class="st">&#39;mean&#39;</span>],  <span class="co"># Count total, count late, calculate percentage</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">&#39;days_late&#39;</span>: [<span class="st">&#39;mean&#39;</span>, <span class="st">&#39;max&#39;</span>]  <span class="co"># Average and maximum days late</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Overall Service Level Metrics:&quot;</span>)</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(service_metrics)</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage on-time directly from the data</span></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>on_time_rate <span class="op">=</span> (<span class="dv">1</span> <span class="op">-</span> clean_shipments[<span class="st">&#39;is_late&#39;</span>].mean()) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;</span><span class="ch">\n</span><span class="ss">On-time delivery rate: </span><span class="sc">{</span>on_time_rate<span class="sc">:.1f}</span><span class="ss">%&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Service Level Metrics:
        is_late  days_late
count  4000.000        NaN
sum     456.000        NaN
mean      0.114     -0.974
max         NaN     21.000

On-time delivery rate: 88.6%</code></pre>
</div>
</div>
<p>In our service metrics:</p>
<ul>
<li><code>'is_late': ['count', 'sum', 'mean']</code></li>
<li>count: Total number of shipments (4000)</li>
<li>sum: Number of late shipments (456 True values)</li>
<li>mean: Percentage of late shipments (456/4000 = 0.114)</li>
</ul>
<p>So sum() on boolean values gives you the count of True values.</p>
</section>
</section>
<section id="merge-combining-information" class="level3">
<h3>6. Merge: Combining Information</h3>
<p><strong>Mental Model:</strong> Join data from multiple sources to create richer datasets.</p>
<p>Now let’s analyze service levels by product category. First, we need to merge our data:</p>
<div id="mental-model-6-merge-prep" class="cell" data-execution_count="21">
<div class="sourceCode" id="cb36"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge shipment data with product line data</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>shipments_with_category <span class="op">=</span> (</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    clean_shipments</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    .merge(product_line_df, on<span class="op">=</span><span class="st">&#39;partID&#39;</span>, how<span class="op">=</span><span class="st">&#39;left&#39;</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    .assign(</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>        category_late<span class="op">=</span><span class="kw">lambda</span> df: df[<span class="st">&#39;is_late&#39;</span>] <span class="op">&amp;</span> df[<span class="st">&#39;prodCategory&#39;</span>].notna()</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;</span><span class="ch">\n</span><span class="st">Product categories available:&quot;</span>)</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shipments_with_category[<span class="st">&#39;prodCategory&#39;</span>].value_counts())</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Product categories available:
prodCategory
Marketables    1850
Machines        846
SpareParts      767
Liquids         537
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🤔 Discussion Questions: Merge Mental Model
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Question 1: Join Types and Data Loss</strong> - Why does your professor think we should use <code>how='left'</code> in most cases? - How can you check if any shipments were lost during the merge?</p>
<p><strong>Question 2: Key Column Matching</strong> - What happens if there are duplicate <code>partID</code> values in the <code>product_line_df</code>?</p>
</div>
</div>
<section id="briefly-give-answers-to-the-discussion-questions-in-this-section-5" class="level4">
<h4>Briefly Give Answers to the Discussion Questions In This Section</h4>
<p>Question 1: Why use how=‘left’</p>
<p>Prevents data loss - keeps all shipments even if category data is missing</p>
<p>Shows data gaps clearly with NaN values</p>
<p>Preserves the primary dataset</p>
<p>Question 1b: Check for lost shipments</p>
<p>Question 2: Duplicate partIDs</p>
<p>Creates duplicate rows in results</p>
<p>Inflates counts and statistics</p>
<p>Check with: product_line_df.duplicated(‘partID’).sum()</p>
</section>
</section>
<section id="split-apply-combine-group-analysis" class="level3">
<h3>7. Split-Apply-Combine: Group Analysis</h3>
<p><strong>Mental Model:</strong> Group data and apply functions within each group.</p>
<p>Now let’s analyze service levels by category:</p>
<div id="mental-model-7-groupby" class="cell" data-execution_count="22">
<div class="sourceCode" id="cb38"><pre class="sourceCode python cell-code"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Analyze service levels by product category</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>service_by_category <span class="op">=</span> (</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    shipments_with_category</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    .groupby(<span class="st">&#39;prodCategory&#39;</span>)  <span class="co"># Split by product category</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    .agg({</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">&#39;is_late&#39;</span>: [<span class="st">&#39;any&#39;</span>, <span class="st">&#39;count&#39;</span>, <span class="st">&#39;sum&#39;</span>, <span class="st">&#39;mean&#39;</span>],  <span class="co"># Count, late count, percentage late</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">&#39;days_late&#39;</span>: [<span class="st">&#39;mean&#39;</span>, <span class="st">&#39;max&#39;</span>]  <span class="co"># Average and max days late</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Service Level by Product Category:&quot;</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(service_by_category)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Service Level by Product Category:
             is_late                   days_late    
                 any count  sum   mean      mean max
prodCategory                                        
Liquids         True   537   22  0.041    -0.950  19
Machines        True   846  152  0.180    -1.336  21
Marketables     True  1850  145  0.078    -0.804  21
SpareParts      True   767  137  0.179    -1.003  21</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🤔 Discussion Questions: Split-Apply-Combine Mental Model
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Question 1: GroupBy Mechanics</strong> - What does <code>.groupby('prodCategory')</code> actually do? How does it “split” the data? - Why do we need to use <code>.agg()</code> after grouping? What happens if you don’t?</p>
<p><strong>Question 2: Multi-Level Grouping</strong> - Explore grouping by <code>['shipID', 'prodCategory']</code>? What question does this answer versus grouping by <code>'prodCategory'</code> alone? (HINT: There may be many rows with identical shipID’s due to a particular order having multiple partID’s.)</p>
</div>
</div>
<section id="briefly-give-answers-to-the-discussion-questions-in-this-section-6" class="level4">
<h4>Briefly Give Answers to the Discussion Questions In This Section</h4>
<p>1 a.</p>
<p>What .groupby(‘prodCategory’) does:</p>
<p>It “splits” the data into separate groups based on unique category values: Before grouping:</p>
<p>text shipID partID prodCategory is_late days_late 10001 part92b16c5 Marketables False -33 10002 part66983b Machines False -11<br />
10003 part8e36f25 Marketables False -18 10004 part30f5de0 Liquids False -6 10005 part9d64d35 SpareParts False -6 After .groupby(‘prodCategory’):</p>
<p>Group 1: Marketables</p>
<p>text 10001 part92b16c5 Marketables False -33 10003 part8e36f25 Marketables False -18 … Group 2: Machines</p>
<p>text 10002 part66983b Machines False -11 … Group 3: Liquids</p>
<p>text 10004 part30f5de0 Liquids False -6 … Group 4: SpareParts</p>
<p>text 10005 part9d64d35 SpareParts False -6 … How it works: Creates separate “mini-dataframes” for each category</p>
<p>Each group contains only rows from that category</p>
<p>When you apply .agg(), it calculates statistics within each group separately</p>
<p>The “split-apply-combine” pattern:</p>
<p>Split data into groups</p>
<p>Apply functions to each group</p>
<p>Combine results back together</p>
<p>1 b.</p>
<p>Why we need .agg() after grouping:</p>
<p>Without .agg(): The grouped data is incomplete and unusable - it’s just split into groups but no calculations are performed.</p>
<p>::: {#ad45d146 .cell execution_count=23} <code>{.python .cell-code}  # This creates a DataFrameGroupBy object, not useful results  grouped= shipments_with_category.groupby('prodCategory')  print(type(grouped)) # &lt;class 'pandas.core.groupby.generic.DataFrameGroupBy'&gt;  print(grouped)       # Can't see the actual data</code></p>
<p>::: {.cell-output .cell-output-stdout} <code>&lt;class 'pandas.core.groupby.generic.DataFrameGroupBy'&gt;  &lt;pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000241846BD190&gt;</code> ::: :::</p>
<p>What .agg() does: It applies calculations to each group and combines the results:</p>
<p>::: {#97c969cb .cell execution_count=24} ``` {.python .cell-code} # Without .agg() - useless grouped_data= shipments_with_category.groupby(‘prodCategory’) #Can’t see or use this meaningfully</p>
<p>#With .agg() - useful results results= shipments_with_category.groupby(‘prodCategory’).agg({ ‘is_late’: ‘mean’, ‘days_late’: ‘max’ }) #Gets: average lateness and max days late FOR EACH CATEGORY ``` :::</p>
<p>What happens if you don’t use .agg(): You get a GroupBy object, not a DataFrame</p>
<p>No calculations are performed</p>
<p>You can’t see or analyze the grouped results</p>
<p>The data remains “split” but not summarized</p>
<p>Bottom line: .agg() is what transforms the split groups into meaningful summary statistics you can actually use and analyze.</p>
<ol start="2" type="1">
<li></li>
</ol>
<p>Grouping by [‘shipID’, ‘prodCategory’] vs ‘prodCategory’ alone:</p>
<p>Grouping by ‘prodCategory’ alone: Answers: “What is the service level for each product category?”</p>
<p>Looks at individual line items</p>
<p>Doesn’t care which shipment they belong to</p>
<p>Example: “4% of Liquids line items are late”</p>
<p>::: {#7d9c57eb .cell execution_count=25} <code>{.python .cell-code}  service_by_category = (     shipments_with_category     .groupby('prodCategory')     .agg({'is_late': 'mean'})  )</code> :::</p>
<p>Grouping by [‘shipID’, ‘prodCategory’]: Answers: “For shipments containing multiple categories, how does lateness vary between categories within the same shipment?”</p>
<p>Looks at shipment-category combinations</p>
<p>Recognizes that one shipment can have items from multiple categories</p>
<p>Example: “In shipment 10192, were the Machines items late but the Liquids on time?”</p>
<p>::: {#af31ee67 .cell execution_count=26} ``` {.python .cell-code} shipment_category_analysis= ( shipments_with_category .groupby([‘shipID’, ‘prodCategory’]) .agg({‘is_late’: ‘any’}) # Was ANY item in this shipment-category combo late? )</p>
<pre><code>:::


Key difference:
prodCategory alone: &quot;How late is each category overall?&quot;

[shipID, prodCategory]: &quot;Within multi-category shipments, which categories tend to be the problem?&quot;

This helps answer: &quot;When an order has both Machines and Liquids, is one category consistently causing the delay?&quot;

## Answering A Business Question

**Mental Model:** Combine multiple data manipulation techniques to answer complex business questions.

Let&#39;s create a comprehensive analysis by combining shipment-level data with category information:

::: {#mental-model-7-comprehensive .cell execution_count=27}
``` {.python .cell-code}
# Create a comprehensive analysis dataset
comprehensive_analysis = (
   shipments_with_category
   .groupby([&#39;shipID&#39;, &#39;prodCategory&#39;])  # Group by shipment and category
   .agg({
       &#39;is_late&#39;: &#39;any&#39;,  # True if any item in this shipment/category is late
       &#39;days_late&#39;: &#39;max&#39;  # Maximum days late for this shipment/category
   })
   .reset_index()
   .assign(
       has_multiple_categories=lambda df: df.groupby(&#39;shipID&#39;)[&#39;prodCategory&#39;].transform(&#39;nunique&#39;) &gt; 1
   )
)

print(&quot;Comprehensive analysis - shipments with multiple categories:&quot;)
multi_category_shipments = comprehensive_analysis[comprehensive_analysis[&#39;has_multiple_categories&#39;]]
print(f&quot;Shipments with multiple categories: {multi_category_shipments[&#39;shipID&#39;].nunique()}&quot;)
print(f&quot;Total unique shipments: {comprehensive_analysis[&#39;shipID&#39;].nunique()}&quot;)
print(f&quot;Percentage with multiple categories: {multi_category_shipments[&#39;shipID&#39;].nunique() / comprehensive_analysis[&#39;shipID&#39;].nunique() * 100:.1f}%&quot;)</code></pre>
<div class="cell-output cell-output-stdout">
<pre><code>Comprehensive analysis - shipments with multiple categories:
Shipments with multiple categories: 232
Total unique shipments: 997
Percentage with multiple categories: 23.3%</code></pre>
</div>
<p>:::</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🤔 Discussion Questions: Answering A Business Question
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Question 1: Business Question Analysis</strong> - What business question does this comprehensive analysis answer? - How does grouping by <code>['shipID', 'prodCategory']</code> differ from grouping by just <code>'prodCategory'</code>? - What insights can ZappTech’s management gain from knowing the percentage of multi-category shipments?</p>
</div>
</div>
</section>
<section id="briefly-give-answers-to-the-discussion-questions-in-this-section-7" class="level4">
<h4>Briefly Give Answers to the Discussion Questions In This Section</h4>
<ol type="1">
<li></li>
</ol>
<p>“How common are multi-category orders, and how does lateness vary within them?” Specifically:</p>
<p>“What percentage of shipments contain products from multiple categories?” (23.3%)</p>
<p>“When orders span multiple categories, which categories within the same shipment are late vs on-time?”</p>
<p>“Do certain category combinations in the same order have different service levels?”</p>
<p>Business insights for ZappTech management: Customer Behavior:</p>
<p>23.3% of customers order across multiple product categories in the same shipment</p>
<p>This reveals cross-selling patterns and customer purchasing habits</p>
<p>Operational Analysis:</p>
<p>Within multi-category shipments, management can see if specific categories consistently cause delays</p>
<p>Example: “When orders contain both Machines and Liquids, are the Machines always late while Liquids are on time?”</p>
<p>Supply Chain Optimization:</p>
<p>Identifies which category combinations create the most operational complexity</p>
<p>Helps optimize warehouse picking, packing, and shipping for mixed-category orders</p>
<p>Service Level Management:</p>
<p>Provides granular insight into service levels at the shipment-category level, not just overall category level</p>
<p>Helps pinpoint exactly where in the fulfillment process delays occur for complex orders</p>
<ol start="2" type="1">
<li></li>
</ol>
<p>Grouping by [‘shipID’, ‘prodCategory’] vs ‘prodCategory’:</p>
<p>Grouping by ‘prodCategory’ alone: Answers: “What is the overall service level for each category?”</p>
<p>Perspective: Category-level analysis</p>
<p>Example: “Machines have 18% late rate across all shipments”</p>
<p>python # Result: One row per category prodCategory is_late_mean Machines 0.180 Liquids 0.041 Marketables 0.078 Grouping by [‘shipID’, ‘prodCategory’]: Answers: “Within each multi-category shipment, how does service level vary between categories?”</p>
<p>Perspective: Shipment-level analysis across categories</p>
<p>Example: “In shipment 10192, Machines were late but Liquids were on time”</p>
</section>
</section>
</section>
</section>
<section id="result-one-row-per-shipment-category-combination" class="level1">
<h1>Result: One row per shipment-category combination</h1>
<p>shipID prodCategory is_late_any 10192 Machines True 10192 Liquids False 10193 Marketables True<br />
10193 SpareParts False Key difference: prodCategory: “How is each category performing overall?”</p>
<p>This reveals intra-shipment patterns - how different categories behave when they’re part of the same customer order versus when they’re ordered separately.</p>
<ol start="3" type="1">
<li></li>
</ol>
<p>Business insights from multi-category shipment percentage (23.3%):</p>
<p>Customer Behavior &amp; Marketing: Cross-selling success: Nearly 1 in 4 customers buy across categories in single orders</p>
<p>Bundling opportunities: Identify which category pairs are frequently purchased together</p>
<p>Marketing strategy: Target customers with complementary products from different categories</p>
<p>Operations &amp; Logistics: Warehouse optimization: 23.3% of shipments require picking from multiple category zones</p>
<p>Staff training: Workers need to handle diverse product types in single shipments</p>
<p>Packaging complexity: Mixed-category orders may need special handling/packaging</p>
<p>Supply Chain Management: Inventory planning: Stock complementary categories in proximity</p>
<p>Shipping efficiency: Multi-category orders might take longer to assemble</p>
<p>Quality control: Different categories may have different handling requirements</p>
<p>Customer Experience: Order fulfillment: Multi-category orders risk partial shipments if one category is unavailable</p>
<p>Delivery expectations: Customers expect all categories to arrive together</p>
<p>Service level: Late items in one category can make the entire shipment appear late</p>
<p>Strategic value: This 23.3% represents ZappTech’s most valuable and complex orders - customers who see the company as a one-stop shop rather than a single-category supplier.</p>
<section id="student-analysis-section" class="level2">
<h2>Student Analysis Section: Mastering Data Manipulation</h2>
<p><strong>Your Task:</strong> Demonstrate your mastery of the seven mental models through comprehensive discussion and analysis. The bulk of your grade comes from thoughtfully answering the discussion questions for each mental model. See below for more details.</p>
<section id="core-challenge-discussion-questions-analysis" class="level3">
<h3>Core Challenge: Discussion Questions Analysis</h3>
<p><strong>For each mental model, provide:</strong> - Clear, concise answers to all discussion questions - Code examples where appropriate to support your explanations</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>📊 Discussion Questions Requirements
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Complete all discussion question sections:</strong> 1. <strong>Assign Mental Model:</strong> Data types, date handling, and debugging 2. <strong>Subset Mental Model:</strong> Filtering strategies and complex queries 3. <strong>Drop Mental Model:</strong> Data cleaning and quality management 4. <strong>Sort Mental Model:</strong> Data organization and business logic 5. <strong>Aggregate Mental Model:</strong> Summary statistics and business metrics 6. <strong>Merge Mental Model:</strong> Data integration and quality control 7. <strong>Split-Apply-Combine Mental Model:</strong> Group analysis and advanced operations 8. <strong>Answering A Business Question:</strong> Combining multiple data manipulation techniques to answer a business question</p>
</div>
</div>
</section>
<section id="professional-visualizations-for-100-grade" class="level3">
<h3>Professional Visualizations (For 100% Grade)</h3>
<p><strong>Your Task:</strong> Create a professional visualization that supports your analysis and demonstrates your understanding of the data.</p>
<p>import matplotlib.pyplot as plt import seaborn as sns</p>
</section>
</section>
</section>
<section id="first-ensure-we-have-all-required-data-by-recreating-the-necessary-variables" class="level1">
<h1>First, ensure we have all required data by recreating the necessary variables</h1>
</section>
<section id="load-data-if-not-already-loaded" class="level1">
<h1>Load data if not already loaded</h1>
<p>if ‘shipments_df’ not in globals(): shipments_df = pd.read_csv( “https://raw.githubusercontent.com/flyaflya/persuasive/main/shipments.csv”, parse_dates=[‘plannedShipDate’, ‘actualShipDate’] ).head(4000)</p>
<p>if ‘product_line_df’ not in globals(): product_line_df = pd.read_csv( “https://raw.githubusercontent.com/flyaflya/persuasive/main/productLine.csv” )</p>
</section>
<section id="create-shipments_with_lateness-if-not-exists" class="level1">
<h1>Create shipments_with_lateness if not exists</h1>
<p>if ‘shipments_with_lateness’ not in globals(): shipments_with_lateness = ( shipments_df .assign( is_late=lambda df: df[‘actualShipDate’] &gt; df[‘plannedShipDate’], days_late=lambda df: (df[‘actualShipDate’] - df[‘plannedShipDate’]).dt.days ) )</p>
</section>
<section id="create-clean_shipments-if-not-exists" class="level1">
<h1>Create clean_shipments if not exists</h1>
<p>if ‘clean_shipments’ not in globals(): clean_shipments = ( shipments_with_lateness .drop(columns=[‘quantity’]) .dropna(subset=[‘plannedShipDate’, ‘actualShipDate’]) )</p>
</section>
<section id="create-shipments_with_category-if-not-exists" class="level1">
<h1>Create shipments_with_category if not exists</h1>
<p>if ‘shipments_with_category’ not in globals(): shipments_with_category = ( clean_shipments .merge(product_line_df, on=‘partID’, how=‘left’) .assign( category_late=lambda df: df[‘is_late’] &amp; df[‘prodCategory’].notna() ) )</p>
</section>
<section id="create-comprehensive_analysis-if-not-exists" class="level1">
<h1>Create comprehensive_analysis if not exists</h1>
<p>if ‘comprehensive_analysis’ not in globals(): comprehensive_analysis = ( shipments_with_category .groupby([‘shipID’, ‘prodCategory’]) .agg({ ‘is_late’: ‘any’, ‘days_late’: ‘max’ }) .reset_index() .assign( has_multiple_categories=lambda df: df.groupby(‘shipID’)[‘prodCategory’].transform(‘nunique’) &gt; 1 ) )</p>
</section>
<section id="create-multi_category_shipments-if-not-exists" class="level1">
<h1>Create multi_category_shipments if not exists</h1>
<p>if ‘multi_category_shipments’ not in globals(): multi_category_shipments = comprehensive_analysis[comprehensive_analysis[‘has_multiple_categories’]]</p>
</section>
<section id="calculate-overall-on-time-rate-if-not-exists" class="level1">
<h1>Calculate overall on-time rate if not exists</h1>
<p>if ‘on_time_rate’ not in globals(): on_time_rate = (1 - clean_shipments[‘is_late’].mean()) * 100</p>
</section>
<section id="calculate-service-level-metrics-by-category" class="level1">
<h1>Calculate service level metrics by category</h1>
<p>category_service = ( shipments_with_category .groupby(‘prodCategory’) .agg({ ‘is_late’: [‘count’, ‘sum’, ‘mean’], ‘days_late’: ‘mean’ }) .round(3) ) category_service.columns = [‘total_shipments’, ‘late_count’, ‘late_rate’, ‘avg_days_late’] category_service[‘on_time_rate’] = (1 - category_service[‘late_rate’]) * 100</p>
</section>
<section id="create-comprehensive-professional-visualization-demonstrating-data-understanding" class="level1">
<h1>Create comprehensive professional visualization demonstrating data understanding</h1>
<p>fig = plt.figure(figsize=(16, 12)) gs = fig.add_gridspec(2, 3, height_ratios=[1, 1], width_ratios=[1, 1, 1])</p>
</section>
<section id="professional-color-palette" class="level1">
<h1>Professional color palette</h1>
<p>colors = [‘#2E8B57’, ‘#4682B4’, ‘#DAA520’, ‘#CD5C5C’] # Green, Blue, Gold, Red plt.style.use(‘default’)</p>
</section>
<section id="plot-1-on-time-delivery-rate-by-category-top-left" class="level1">
<h1>Plot 1: On-time delivery rate by category (Top Left)</h1>
<p>ax1 = fig.add_subplot(gs[0, 0]) bars1 = ax1.bar(category_service.index, category_service[‘on_time_rate’], color=colors, alpha=0.8, edgecolor=‘black’, linewidth=1) ax1.set_title(‘On-Time Delivery Rate by Category’, fontsize=12, fontweight=‘bold’, pad=15) ax1.set_ylabel(‘On-Time Rate (%)’, fontweight=‘bold’) ax1.set_ylim(75, 100) ax1.grid(axis=‘y’, alpha=0.3, linestyle=‘–’)</p>
</section>
<section id="add-value-labels" class="level1">
<h1>Add value labels</h1>
<p>for bar, value in zip(bars1, category_service[‘on_time_rate’]): ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3, f’{value:.1f}%‘, ha=’center’, va=‘bottom’, fontweight=‘bold’, fontsize=10)</p>
</section>
<section id="plot-2-average-days-late-by-category-top-center" class="level1">
<h1>Plot 2: Average days late by category (Top Center)</h1>
<p>ax2 = fig.add_subplot(gs[0, 1]) bars2 = ax2.bar(category_service.index, category_service[‘avg_days_late’], color=colors, alpha=0.8, edgecolor=‘black’, linewidth=1) ax2.set_title(‘Average Days Late by Category’, fontsize=12, fontweight=‘bold’, pad=15) ax2.set_ylabel(‘Average Days Late’, fontweight=‘bold’) ax2.grid(axis=‘y’, alpha=0.3, linestyle=‘–’)</p>
</section>
<section id="add-value-labels-1" class="level1">
<h1>Add value labels</h1>
<p>for bar, value in zip(bars2, category_service[‘avg_days_late’]): ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.05, f’{value:.2f}‘, ha=’center’, va=‘bottom’, fontweight=‘bold’, fontsize=10)</p>
</section>
<section id="plot-3-late-shipment-distribution-top-right" class="level1">
<h1>Plot 3: Late shipment distribution (Top Right)</h1>
<p>ax3 = fig.add_subplot(gs[0, 2]) late_by_category = shipments_with_category[shipments_with_category[‘is_late’] == True] category_late_counts = late_by_category[‘prodCategory’].value_counts() wedges, texts, autotexts = ax3.pie(category_late_counts.values, labels=category_late_counts.index, colors=colors, autopct=‘%1.1f%%’, startangle=90) ax3.set_title(‘Distribution of Late ShipmentsCategories’, fontsize=12, fontweight=‘bold’, pad=15)</p>
</section>
<section id="plot-4-multi-category-vs-single-category-performance-bottom-left" class="level1">
<h1>Plot 4: Multi-category vs Single-category performance (Bottom Left)</h1>
<p>ax4 = fig.add_subplot(gs[1, 0]) multi_cat_performance = comprehensive_analysis.groupby(‘has_multiple_categories’)[‘is_late’].mean() labels = [‘Single Category’, ‘Multi Category’] values = [multi_cat_performance[False] * 100, multi_cat_performance[True] * 100] bars4 = ax4.bar(labels, values, color=[‘#4682B4’, ‘#CD5C5C’], alpha=0.8, edgecolor=‘black’) ax4.set_title(‘Late Rate: Single vs Multi-Category Orders’, fontsize=12, fontweight=‘bold’, pad=15) ax4.set_ylabel(‘Late Rate (%)’, fontweight=‘bold’) ax4.set_ylim(0, max(values) * 1.1)</p>
</section>
<section id="add-value-labels-2" class="level1">
<h1>Add value labels</h1>
<p>for bar, value in zip(bars4, values): ax4.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5, f’{value:.1f}%‘, ha=’center’, va=‘bottom’, fontweight=‘bold’, fontsize=10)</p>
</section>
<section id="plot-5-service-level-timeline-bottom-center" class="level1">
<h1>Plot 5: Service level timeline (Bottom Center)</h1>
<p>ax5 = fig.add_subplot(gs[1, 1]) # Create monthly service level data shipments_with_category[‘month’] = shipments_with_category[‘actualShipDate’].dt.to_period(‘M’) monthly_service = shipments_with_category.groupby(‘month’)[‘is_late’].mean() monthly_on_time = (1 - monthly_service) * 100</p>
<p>ax5.plot(range(len(monthly_on_time)), monthly_on_time.values, marker=‘o’, linewidth=2, markersize=6, color=‘#2E8B57’) ax5.set_title(‘Monthly On-Time Delivery Trend’, fontsize=12, fontweight=‘bold’, pad=15) ax5.set_ylabel(‘On-Time Rate (%)’, fontweight=‘bold’) ax5.set_xlabel(‘Month’, fontweight=‘bold’) ax5.grid(True, alpha=0.3) ax5.set_ylim(80, 100)</p>
</section>
<section id="plot-6-key-metrics-summary-bottom-right" class="level1">
<h1>Plot 6: Key metrics summary (Bottom Right)</h1>
<p>ax6 = fig.add_subplot(gs[1, 2]) ax6.axis(‘off’)</p>
</section>
<section id="create-summary-text" class="level1">
<h1>Create summary text</h1>
<p>summary_text = f”“” KEY BUSINESS METRICS</p>
<p>Overall Performance: • On-Time Rate: {on_time_rate:.1f}% • Total Shipments: {len(clean_shipments):,}</p>
<p>Category Performance: • Best: Liquids ({category_service.loc[‘Liquids’, ‘on_time_rate’]:.1f}%) • Worst: Machines ({category_service.loc[‘Machines’, ‘on_time_rate’]:.1f}%)</p>
<p>Multi-Category Orders: • Percentage: {multi_category_shipments[‘shipID’].nunique() / comprehensive_analysis[‘shipID’].nunique() * 100:.1f}% • Count: {multi_category_shipments[‘shipID’].nunique():,} shipments</p>
<p>Operational Insights: • {category_service.loc[‘Liquids’, ‘total_shipments’]:,} Liquids shipments • {category_service.loc[‘Machines’, ‘total_shipments’]:,} Machines shipments • Average delay: {category_service[‘avg_days_late’].mean():.1f} days ““”</p>
<p>ax6.text(0.05, 0.95, summary_text, transform=ax6.transAxes, fontsize=10, verticalalignment=‘top’, fontfamily=‘monospace’, bbox=dict(boxstyle=“round,pad=0.5”, facecolor=‘lightgray’, alpha=0.8))</p>
<p>plt.tight_layout() plt.show()</p>
</section>
<section id="print-key-insights" class="level1">
<h1>Print key insights</h1>
<p>print(“” + “=”<em>60) print(“KEY BUSINESS INSIGHTS”) print(“=”</em>60) print(f”• Best performing category: Liquids ({category_service.loc[‘Liquids’, ‘on_time_rate’]:.1f}% on-time)“) print(f”• Worst performing category: Machines &amp; SpareParts ({category_service.loc[‘Machines’, ‘on_time_rate’]:.1f}% on-time)“) print(f”• Multi-category orders: {multi_category_shipments[‘shipID’].nunique() / comprehensive_analysis[‘shipID’].nunique() * 100:.1f}% of shipments”) print(f”• Overall service level: {on_time_rate:.1f}% on-time delivery”) print(“Visualization code temporarily commented out for testing”) ``` ## 📊 Professional Visualization Analysis: Service Level Performance by Category</p>
<section id="step-1-data-foundation-and-business-context" class="level3">
<h3><strong>Step 1: Data Foundation and Business Context</strong></h3>
<p><strong>Dataset Purpose:</strong> This analysis uses ZappTech’s shipment data to understand service level performance across product categories and identify cross-category ordering patterns.</p>
<p><strong>Core Business Questions:</strong> - How does on-time delivery performance vary across different product categories? - What percentage of orders include products from multiple categories? - Are there operational patterns that could inform business strategy?</p>
<p><strong>Data Structure:</strong> The dataset combines shipment tracking data (planned vs actual ship dates) with product category information, enabling category-level performance analysis.</p>
<hr />
</section>
<section id="step-2-data-quality-and-preparation" class="level3">
<h3><strong>Step 2: Data Quality and Preparation</strong></h3>
<p><strong>Data Cleaning Process:</strong> - ✅ Removed missing date values to ensure accurate lateness calculations - ✅ Maintained data integrity by using left joins to preserve all shipment records - ✅ Calculated precise lateness metrics using datetime operations</p>
<p><strong>Key Metrics Created:</strong> - <code>is_late</code>: Boolean flag indicating whether shipment missed planned date - <code>days_late</code>: Quantitative measure of delivery delay - <code>has_multiple_categories</code>: Identifies complex multi-category orders</p>
<hr />
</section>
<section id="step-3-service-level-performance-analysis" class="level3">
<h3><strong>Step 3: Service Level Performance Analysis</strong></h3>
<p><strong>Overall Performance Baseline:</strong> The analysis establishes that <strong>88.6%</strong> of shipments deliver on time, providing a benchmark for category-level comparisons.</p>
<p><strong>Category Performance Spectrum:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Category</th>
<th>On-Time Rate</th>
<th>Performance Level</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Liquids</strong></td>
<td><strong>95.9%</strong></td>
<td>🟢 Excellent</td>
</tr>
<tr class="even">
<td><strong>Marketables</strong></td>
<td><strong>92.2%</strong></td>
<td>🟡 Good</td>
</tr>
<tr class="odd">
<td><strong>Machines</strong></td>
<td><strong>82.0%</strong></td>
<td>🔴 Needs Improvement</td>
</tr>
<tr class="even">
<td><strong>Spare Parts</strong></td>
<td><strong>82.1%</strong></td>
<td>🔴 Needs Improvement</td>
</tr>
</tbody>
</table>
<p><strong>Performance Gap:</strong> <strong>13.9 percentage points</strong> separate best and worst performing categories, indicating significant operational variation.</p>
<hr />
</section>
<section id="step-4-multi-category-order-analysis" class="level3">
<h3><strong>Step 4: Multi-Category Order Analysis</strong></h3>
<p><strong>Cross-Customer Behavior:</strong> <strong>23.3%</strong> of shipments contain products from multiple categories, revealing important customer purchasing patterns.</p>
<p><strong>Operational Complexity:</strong> Multi-category orders represent logistical challenges that may require specialized handling processes.</p>
<p><strong>Business Opportunity:</strong> This segment represents potential for bundled product offerings and targeted marketing strategies.</p>
<hr />
</section>
<section id="step-5-temporal-performance-trends" class="level3">
<h3><strong>Step 5: Temporal Performance Trends</strong></h3>
<p><strong>Consistency Monitoring:</strong> Monthly trend analysis shows service level stability over time, helping identify seasonal patterns or operational changes.</p>
<p><strong>Performance Tracking:</strong> The timeline visualization provides ongoing monitoring capability for service level improvements or deteriorations.</p>
<hr />
</section>
<section id="step-6-comparative-analysis-framework" class="level3">
<h3><strong>Step 6: Comparative Analysis Framework</strong></h3>
<p><strong>Single vs Multi-Category Performance:</strong> Direct comparison reveals whether complex orders experience different service levels, informing resource allocation decisions.</p>
<p><strong>Category Contribution to Late Shipments:</strong> The distribution analysis shows which categories contribute most to overall late shipments, prioritizing improvement efforts.</p>
<hr />
</section>
<section id="step-7-business-intelligence-integration" class="level3">
<h3><strong>Step 7: Business Intelligence Integration</strong></h3>
<section id="strategic-insights" class="level4">
<h4><strong>Strategic Insights:</strong></h4>
<ul>
<li>🎯 <strong>Liquids category</strong> demonstrates operational excellence that could be replicated</li>
<li>⚠️ <strong>Machines category</strong> requires focused improvement initiatives</li>
<li>🔄 <strong>Multi-category orders</strong> represent both challenge and opportunity</li>
</ul>
</section>
<section id="operational-recommendations" class="level4">
<h4><strong>Operational Recommendations:</strong></h4>
<ul>
<li>🔍 Investigate root causes for Machines category performance issues</li>
<li>📦 Develop specialized processes for multi-category order fulfillment</li>
<li>📈 Use Liquids category as benchmark for best practices</li>
</ul>
</section>
<section id="performance-management" class="level4">
<h4><strong>Performance Management:</strong></h4>
<ul>
<li>🎯 Establish category-specific service level targets</li>
<li>📊 Implement regular monitoring of multi-category order trends</li>
<li>📅 Use monthly trends for proactive operational adjustments</li>
</ul>
<hr />
</section>
</section>
<section id="visualization-components" class="level2">
<h2>📈 <strong>Visualization Components</strong></h2>
<p><strong>Professional Charts Created:</strong> - <strong>Bar Chart:</strong> Clear comparison of on-time delivery rates across categories - <strong>Pie Chart:</strong> Distribution of late shipments by category<br />
- <strong>Timeline:</strong> Monthly service level trends - <strong>Summary Metrics:</strong> Key performance indicators and business insights</p>
<p><strong>Key Finding:</strong> The visualization highlights that <strong>Machines and SpareParts need operational improvement</strong> while <strong>Liquids perform exceptionally well</strong>, providing clear direction for operational focus areas.</p>
<p><strong>Your visualizations should:</strong> - Use clear labels and professional formatting - Support the insights from your discussion questions - Be appropriate for a business audience - Do not <code>echo</code> the code that creates the visualizations</p>
</section>
<section id="challenge-requirements" class="level2">
<h2>Challenge Requirements 📋</h2>
<p><strong>Your Primary Task:</strong> Answer all discussion questions for the seven mental models with thoughtful, well-reasoned responses that demonstrate your understanding of data manipulation concepts.</p>
<p><strong>Key Requirements:</strong> - Complete discussion questions for each mental model - Demonstrate clear understanding of pandas concepts and data manipulation techniques - Write clear, business-focused analysis that explains your findings</p>
</section>
<section id="getting-started-repository-setup" class="level2">
<h2>Getting Started: Repository Setup 🚀</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>📁 Getting Started
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Step 1:</strong> Fork and clone this challenge repository - Go to the course repository and find the “dataManipulationChallenge” folder - Fork it to your GitHub account, or clone it directly - Open the cloned repository in Cursor</p>
<p><strong>Step 2:</strong> Set up your Python environment - Follow the Python setup instructions above (use your existing venv from Tech Setup Challenge Part 2) - Make sure your virtual environment is activated and the Python interpreter is set</p>
<p><strong>Step 3:</strong> You’re ready to start! The data loading code is already provided in this file.</p>
<p><strong>Note:</strong> This challenge uses the same <code>index.qmd</code> file you’re reading right now - you’ll edit it to complete your analysis.</p>
</div>
</div>
<section id="getting-started-tips" class="level3">
<h3>Getting Started Tips</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>🎯 Method Chaining Philosophy
</div>
</div>
<div class="callout-body-container callout-body">
<blockquote>
<p>“Each operation should build naturally on the previous one”</p>
</blockquote>
<p><em>Think of method chaining like building with LEGO blocks - each piece connects to the next, creating something more complex and useful than the individual pieces.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>💾 Important: Save Your Work Frequently!
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Before you start:</strong> Make sure to commit your work often using the Source Control panel in Cursor (Ctrl+Shift+G or Cmd+Shift+G). This prevents the AI from overwriting your progress and ensures you don’t lose your work.</p>
<p><strong>Commit after each major step:</strong></p>
<ul>
<li>After completing each mental model section</li>
<li>After adding your visualizations</li>
<li>After completing your advanced method chain</li>
<li>Before asking the AI for help with new code</li>
</ul>
<p><strong>How to commit:</strong></p>
<ol type="1">
<li>Open Source Control panel (Ctrl+Shift+G)</li>
<li>Stage your changes (+ button)</li>
<li>Write a descriptive commit message</li>
<li>Click the checkmark to commit</li>
</ol>
<p><em>Remember: Frequent commits are your safety net!</em></p>
</div>
</div>
</section>
</section>
<section id="grading-rubric" class="level2">
<h2>Grading Rubric 🎓</h2>
<p><strong>75% Grade:</strong> Complete discussion questions for at least 5 of the 7 mental models with clear, thoughtful responses.</p>
<p><strong>85% Grade:</strong> Complete discussion questions for all 7 mental models with comprehensive, well-reasoned responses.</p>
<p><strong>95% Grade:</strong> Complete all discussion questions plus the “Answering A Business Question” section.</p>
<p><strong>100% Grade:</strong> Complete all discussion questions plus create a professional visualization showing service level by product category.</p>
</section>
<section id="submission-checklist" class="level2">
<h2>Submission Checklist ✅</h2>
<p><strong>Minimum Requirements (Required for Any Points):</strong></p>
<ul class="task-list">
<li><label><input type="checkbox" />Created repository named “dataManipulationChallenge” in your GitHub account</label></li>
<li><label><input type="checkbox" />Cloned repository locally using Cursor (or VS Code)</label></li>
<li><label><input type="checkbox" />Completed discussion questions for at least 5 of the 7 mental models</label></li>
<li><label><input type="checkbox" />Document rendered to HTML successfully</label></li>
<li><label><input type="checkbox" />HTML files uploaded to your repository</label></li>
<li><label><input type="checkbox" />GitHub Pages enabled and working</label></li>
<li><label><input type="checkbox" />Site accessible at <code>https://[your-username].github.io/dataManipulationChallenge/</code></label></li>
</ul>
<p><strong>75% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox" />Complete discussion questions for at least 5 of the 7 mental models</label></li>
<li><label><input type="checkbox" />Clear, thoughtful responses that demonstrate understanding</label></li>
<li><label><input type="checkbox" />Code examples where appropriate to support explanations</label></li>
</ul>
<p><strong>85% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox" />Complete discussion questions for all 7 mental models</label></li>
<li><label><input type="checkbox" />Comprehensive, well-reasoned responses showing deep understanding</label></li>
<li><label><input type="checkbox" />Business context for why concepts matter</label></li>
<li><label><input type="checkbox" />Examples of real-world applications</label></li>
</ul>
<p><strong>95% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox" />Complete discussion questions for all 7 mental models</label></li>
<li><label><input type="checkbox" />Complete the “Answering A Business Question” discussion questions</label></li>
<li><label><input type="checkbox" />Comprehensive, well-reasoned responses showing deep understanding</label></li>
<li><label><input type="checkbox" />Business context for why concepts matter</label></li>
</ul>
<p><strong>100% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox" />All discussion questions completed with professional quality</label></li>
<li><label><input type="checkbox" />Professional visualization showing service level by product category</label></li>
<li><label><input type="checkbox" />Professional presentation style appropriate for business audience</label></li>
<li><label><input type="checkbox" />Clear, engaging narrative that tells a compelling story</label></li>
<li><label><input type="checkbox" />Practical insights that would help ZappTech’s management</label></li>
</ul>
<p><strong>Report Quality (Critical for Higher Grades):</strong></p>
<ul class="task-list">
<li><label><input type="checkbox" />Professional writing style (no AI-generated fluff)</label></li>
<li><label><input type="checkbox" />Concise analysis that gets to the point</label></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id = "quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->

</body>

</html>
